# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Network Science Summer Research Institute 
# the base hostname & protocol for your site
url: "http://gdancik.github.io/NS-SRI" 
baseurl: "/NS-SRI"
# Build settings
markdown: kramdown
timezone: America/New_York
course: Network Science Summer Research Institute

